import './globals.css'


export const metadata = {
  title: 'Jogo Da Memoria',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body> <header className=''>
        
        <h1>JOGO DA MEMORIA</h1>
        <div>
          <h1>LOGOUT</h1>
          <h1>SOBRE</h1>
        </div>
      </header></body>
    </html>
  )
}
