import './globals.css'
import Menu from '@/components/menu'



export const metadata = {
  title: 'Jogo Da Memoria',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className='bg-[#3A3A3A]'>
        <header>
        <Menu logolink={""} logo={"JOGO DA MEMÓRIA"} textolink1={""} texto1={"LOGOUT"} textolink2={""} texto2={"SOBRE"}></Menu>

        
        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
