import "./globals.css";

export const metadata = {
  title: "Jogo Da Memoria",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className="bg-[#3A3A3A]">

        <main>{children}</main>
      </body>
    </html>
  );
}
